### ISSUE TITLE
logtool-examples: BrokerAccounting

### ISSUE THREAD

**Issue by pkings** [powertac/powertac-server#1021]
The decimal separator is "," on german machines so that you can not differentiate between column separation and decimal separation. You could either use ";" for column separation or force the output to be US NumberFormat.
`NumberFormat nf = NumberFormat.getNumberInstance(Locale.US);
private DecimalFormat decimalFormat = (DecimalFormat)nf;
`
`output.format("'minDuration':%d,'signup':%s,'withdraw':%s,'periodic':%s,",
              tariff.getMinDuration(), decimalFormat.format(tariff.getSignupPayment()),
              decimalFormat.format(tariff.getEarlyWithdrawPayment()), decimalFormat.format(tariff.getPeriodicPayment()));
`
(example from TariffAnalysis.java)

**Comment by jecollins** [comment]
I think going to US number format would be less disruptive; otherwise existing tools that read the output files could break. This will need to be done in all the tools that generate csv tables.

**Comment by jecollins** [comment]
BrokerAccounting is updated to use US number format. The output is more compact because it omits trailing zeros. I'll work through the rest of the analyzers that produce csv files. In some ways this approach is simpler, because numeric resolution is set in one place, and could easily be a parameter. Groupings (the commas in xxx,xxx.xx) are turned off because they conflict with the csv format and they complicate parsing.
