### ISSUE TITLE
Time to migrate to Java 11 LTS

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1023]
Java 8 is no longer supported, and at least one user is [having problems](http://power-tac-developers.975333.n3.nabble.com/Trouble-getting-sample-broker-to-connect-to-local-server-tt4027016.html) possibly related to changes between Java 8 and Java 11 (or Java 12 in this case).

I suggest updating the snapshot first, then doing a point release of 1.6. Of course, once we do this, users will need to update their systems to take advantage of further updates.

**Comment by govertbuijs** [comment]
This change has a dependency on the server-side Java version. I'll have to check with SysAdmin is Java 11 is supported. I think the servers are scheduled to be upgraded to a newer Red Hat, so it probably isn't an issue.

**Comment by erikkemperman** [comment]
I've been fighting with Java 11 for a while -- pushed the work in progress to github (powertac-core, -server and sample-broker) in branches called "java11" if anyone is interested.

There a a bunch of issues:
- aspectj maven plugin doesn't support java 11 yet. There's a fork which I am using now but I guess we'd prefer to stick with the official plugin. See https://github.com/mojohaus/aspectj-maven-plugin/pull/45.
- In the long run we are going to get in trouble with xstream, it appears the newer java versions are more strict about the kind of tricks to xstream uses to serialize. For now this just emits warnings but future versions are just going to break, if I read this correctly: https://github.com/x-stream/xstream/issues/101
- All unit tests pass, except for the visualizer2. No idea yet what's happenening there, it's all very opaque and difficult to debug due to aspects/proxies and whatnot.

However, when I just attempt to run a boot and a sim then it seems that things more or less work -- at least for the usual scenarios.

**Comment by erikkemperman** [comment]
FYI I think I fixed most of the issues in visualizer2, the tests pass and quick attempt to run boot/sim worked well.

The problems with aspectj plugin and xstream remain, of course. But we have a working java 11 setup I think and we can resolve these as solutions become available / apparent.

**Comment by erikkemperman** [comment]
Made some PRs, see references above.

**Comment by jecollins** [comment]
The master branch now works with Java 11. There remain some warnings about reflection access that will need to be addressed eventually.
