### ISSUE TITLE
System build and javadoc generation not working

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1039]
The recent changes for Issue #1031 include two new classes and a couple updates to existing classes. None of these show up in the generated javadocs, and in fact the Travis CI dashboard does not even include powertac-core or powertac-server. Instead it includes many of the old separate components, which are now empty and of course cannot be built. It's hard to know when the javadocs were last generated. It appears to have been sometime this year, since the bottom of each page shows "Copyright 2019".

**Comment by erikkemperman** [comment]
Hi John,

- There seems to be something wrong indeed with the pipeline that should publish the javadocs, latest succesful build on https://github.com/powertac/powertac.github.io was 3 months ago. I will investigate.

- Your most recent commit on powertac-core did not pass the build; a failed unit test: https://travis-ci.org/powertac/powertac-core/builds/624899194#L590. Notice also the red cross behind the commit here: https://github.com/powertac/powertac-core/commits/master. Did you not get an email from github or travis that the build failed? We might have to configure notifications I suppose, I'd assumed that the committer of an offending commit would be notified of broken mergers. 

- I'm not sure what you mean by "Travis dashboard"? If I look here I see all our repositories, including the actively maintained ones: https://travis-ci.org/powertac/

**Comment by erikkemperman** [comment]
Weird -- now I can't reproduce the failing unit test in powertac-core. And the build which I triggered by commits to master just now passed. Is it possible this test somehow fails intermittently / indeterministically? Here is the link again to the relevant line in the travis log: https://travis-ci.org/powertac/powertac-core/builds/624899194#L590

I think I have resolved the issue with javadoc not deploying. It seems recent versions of various maven plugins are more pedantic about validating our POMs. And actually, of dependencies as well. This keeps causing headaches, because those are outside of our control.

Furthermore, due to some combination of plugin upgrades and commits by us the paths on the Travis machines to the built javadoc has changed. Not exactly sure how that happened but I had to change it to make it work again.

Also it seems that development of the maven plugins proceeds at glacial speeds. We still need the fork of the aspectj plugin because they won't apparently merge this into the main one. For other reasons it would be great if we could use the 3.0.1 version of the maven-project-info-report plugin -- which is "released" on github but not actually deployed at mvncentral.

On the other hand it looks like we can finally get rid of the ugly override we had on some deep dependency due to activemq so I guess it's not all bad :-)

So anyway, the docs are here:
https://powertac.github.io/server/master/apidocs/index.html

Does that look all right?

**Comment by jecollins** [comment]
That test is checking whether old entries in the OrderbookRepo are getting cleaned up properly. Probably the test should be for a range, which should be more than are needed to compose a boot record and fewer than 500. I'm surprised it would not be deterministic, but the actual correct number is very hard to compute. I'll see if I can update the test.

**Comment by jecollins** [comment]
I updated OrderbookRepoTests to accept a range of values to avoid needing to recompute the correct value when dependencies change, since some dependencies may affect the exact number without affecting the functionality.
