### ISSUE TITLE
Auth Fail on downloading evcustomer

### ISSUE THREAD

**Issue by MunhozThiago** [powertac/powertac-server#810]
Hi again,

After the new update, the evcustomer module is now requested when cloning the powertac-server project, but I am getting now another error: Auth fail.

It does not allow me to clone the project.

![error](https://cloud.githubusercontent.com/assets/6729959/6688904/d70d2594-ccae-11e4-9f5d-7642b424e8ea.png)

**Comment by govertbuijs** [comment]
Hi,

What is the exact command and /or software you used to clone the repo?
I've tried with git clone --recursive git://github.com/powertac/powertac-server.git on the command line and didn't get an error.

Note : both John and i are on Linux, and i gather you're using Windows.
If this is a Windows specific problem, you might have more luck on the [Nabble Power TAC] (http://power-tac-developers.975333.n3.nabble.com/) mailing list.

**Comment by jecollins** [comment]
Most likely you have not uploaded an ssh key to your github account for the machine you are using. This is probably happening because I added the evcustomer module as a RW repo rather than a RO repo (which would have been an https:// URL rather than git@github.com: URL). I'll see if I can fix that, but it may take some experimentation.

**Comment by jecollins** [comment]
Please let me know or close this issue if it's resolved. Thanks.

**Comment by jecollins** [comment]
I have not heard back, but there have been no other complaints about this. Time to close it.
