### ISSUE TITLE
Reconsider price formation in wholesale market

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#878]
Currently, the Power TAC scenario involves three markets (wholesale, retail, balancing), all of which are scoped to a single distribution grid. This setup gives individual brokers unrealistically high market power in the wholesale market, because the Power TAC distribution grid should be thought of as one of many distribution grids in the market. One consequence of this setup is that it is possible for individual brokers to "corner" the wholesale market. Ideally, the market power of an individual broker would be scaled down by the ratio of the Power TAC grid to the total of all customers across all distribution grids served by the wholesale market -- probably 100:1 at least. The question is how to do this. Does it require the wholesale market to predict overall demand? This is what happens in the real world. We could then expose a portion of the price curve to the Power TAC brokers, rather than the whole curve, since the limited market power of the Power TAC brokers should not permit them to see the entire curve.

**Comment by jecollins** [comment]
A simple way to make this work would be to

- multiply the capacity of the wholesale market by at least an order of magnitude,
- update the "buyer" agent to represent the collection of other distribution grids;
- the buyer would predict net demand, possibly with lower penetration of solar and EVs than the PowerTAC scenario,
- the buyer would buy and sell to track its prediction of its own net demand as it evolves toward the current timeslot.

**Comment by mansarin** [comment]
One other way would be to use real world data for the wholesale market. Increase the capacity traded in the wholesale market so it is similar to a real world market by: 

- set the buyer’s net demand to be similar to the regional net demand curve of that market with some noise
- Remove a small amount that mirrors the Power TAC scenario’s demand. 

In this case, the wholesale market operates at a much higher energy level and the buyer buys most of the cleared volume. The Power TAC brokers, which buy a small percentage of the cleared volume, have minimal influence on prices. I imagine if we mirrored the real world, their influence would be negligible (0.1% or less). Broker's influence can be amplified if they should be active participants in the wholesale market as well.

One problem with this approach is what kind of data to include. Regularly, wholesale markets are dependent on regional weather conditions; on hot days in California, electricity use tends to spike, since many consumers turn on their air conditioning. Brokers should be able to use this predictability to their advantage. It would be important to take weather forecast and wholesale market data from the same region, so that correlations can be preserved.

Would there be any other possible problems with using real-world data for the wholesale market?

**Comment by mansarin** [comment]
Also, does the Power TAC wholesale market have a minimum bid quantity? Do real-world markets have minimum bid quantities? Any thoughts on this alignment?

**Comment by jecollins** [comment]
Yes, there is a minimum bid quantity. We've kept it relatively low (10 kWh) to give brokers maximum opportunity to achieve balance.

**Comment by jecollins** [comment]
We now have a MisoBuyer agent in the wholesale market that buys according to a timeseries modeled on two years of actual (weather-dependent) demand from the north-central MISO wholesale market. The configuration may need a bit of tweaking, but at this point the MisoBuyer demand is configured to be about 10x the size of the Power TAC demand. This requires modifying the price curve (in CpGenco) to expand quantities by about 11x. The market-position limits in accounting are raised to quantities well above the highest demand seen in the Power TAC scenario, effectively disabling them.
