### ISSUE TITLE
Inner subclasses of @Domain types should not be logged

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#895]
This includes Rate$ProbeCharge and DefaultUtilityOptimizer$DummyTariffSubscription, which are inner subclasses of @Domain classes. Perhaps we need another annotation to cover this case?

**Comment by erikkemperman** [comment]
Actually, I'm not sure if these show up in the logs due to their being inner classes of @Domain-annotated classes, or because both of them are subclasses of (other) @Domain-annotated classes (TarriffSubscription and HourlyCharge)?

**Comment by jecollins** [comment]
I believe they show up because they call the superclass constructor. I can see two possible solutions: (1) don't call the superclass constructor, or (2) make the @Domain class and the non-domain class be subclasses of a non-domain superclass.

**Comment by erikkemperman** [comment]
Played around for a bit:
- removing the `@Domain` annotation on DefaultUtilityOptimizer (outer class) does _not_ get rid of the DummyTariffSubscription lines in state log;
- removing the annotation on TariffSubscription (super class)  _does_ get of those lines.

I believe this proves that the super-constructor call is in fact the culprit here.

I'm not sure what you mean by your possible solution (1), as far as I know it's a compile-time error to not call the super-constructor (unless the superclass has a zero-arg constructor, which is then called implicitly)? 

If I understand your possible solution (2) correctly it seems to me to be fixing this issue in the wrong place, sort of. We'd have an otherwise bogus class with all of the logic, just so we can re-use it in classes with and without the `@Domain` annotation.

I'm trying to get a third alternative working, namely your original suggestion of introducing a `@DomainIgnore` annotation. Will let you know if that works out, or not.

**Comment by erikkemperman** [comment]
Hm, I've tried a few things but so far have been unable to get this to work -- except by changing the `StateLogging.newstate()` method to check for a `DomainIgnore` annotation at run-time via reflection. I think that might still be slightly cleaner than other proposed alternatives... What do you think?

I thought it might be possible with just a new pointcut but I guess the problem is that the superclass is compiled (and woven) before the subclass, so the logging call is already in the bytecode when the subclass is compiled.

**Comment by jecollins** [comment]
I think this is a good alternative. In fact, it may be enough to simply ignore the @Domain annotation for subclasses. The only @Domain types I can think of that are subclasses are Rate and RegulationRate, but in this case the superclass RateCore is not a @Domain type.

So how do we discover that the constructor is called from a subclass constructor? Perhaps by looking at the first element of the stacktrace? If that class is a subclass of the current class, then don't record, because presumably if the subclass also has the @Domain annotation, it would have already been recorded.

**Comment by erikkemperman** [comment]
I was planning to do a little profiling tomorrow, to see if the extra overhead of runtime reflection isn't too bad. It should be all right, I expect.

But I guess you're right that we might not strictly need a separate `@DomainIgnore` annotation, except perhaps for code clarity.

For the (currently non-existent, I think) case where both super- and subclass have `@Domain`, wouldn't we prefer to see the more specific (sub)class in the logs? And actually I'm not sure if it's unreasonable to have both, in that case.

I would have to double check, but I don't think we'd need to fill in the stack trace (which is costly, I seem to remember) -- since the annotation doesn't have an `@Inherit` meta-annotation, we could just double check at runtime if the class at hand has `@Domain`?

By the way, I also considered using the `@ChainedConstructor` annotation for this, which seems to me to handle a similar case -- except it's for `this(...)` calls rather than `super(...)`. But that doesn't work in cases where subclasses are in a different module, because of the compile-time weaving.

**Comment by jecollins** [comment]
I think the @DomainIgnore idea won't work unless you also use the stack trace to discover that the call was from a constructor in a class with that annotation. So it's more (runtime and programming and testing) work than just implementing a rule that @Domain does not apply to subclasses.

**Comment by erikkemperman** [comment]
Might have been unclear earlier, sorry. I already have that working. Note that the `thing` we get  from [`jp.getTarget()`](https://github.com/powertac/powertac-aop/blob/master/src/main/java/org/powertac/common/state/StateLogging.java#L86), at runtime within `StateLogging.newstate()`, is an instance of the _subclass_ (otherwise we wouldn't have inner classes in the state log to begin with :-))

**Comment by erikkemperman** [comment]
It still might be better to not have an extra class, of course, just saying it would work if we wanted it :-)

**Comment by jecollins** [comment]
Yes, I had not made that connection. But if target is the subclass, then why is the joinpoint even detected, and why does it use the annotation from the superclass? The behavior seems to indicate that the joinpoint is detected when the super() method is called.

**Comment by erikkemperman** [comment]
I think the bytecode for the super constructor already contains a call to the `newstate` method, because it matches the joinpoint when we compile it, before we get around to compiling the subclasses in another module.

So when the subclass calls the superconstructor, `newstate` is invoked for that reason, but then when we do `jp.getTarget()` within that method, we obtain the subclass instance (in the same way that `this` in a superconstructor is still the subclass instance). Does that make sense?

So I'm now thinking we can just double check that the `thing.getClass()` has the `@Domain` annotation and -- since that annotation isn't inherited -- I think all bases are covered.

**Comment by jecollins** [comment]
Sounds good. I'm glad we're (or you are) finally understanding this stuff. Thanks.

**Comment by erikkemperman** [comment]
I'll try to get this sorted tomorrow.

**Comment by erikkemperman** [comment]
I think this is about right:
https://github.com/powertac/powertac-aop/pull/1

I've also made PRs of some earlier commits, adding weaving to factored-customer:
https://github.com/powertac/factored-customer/pull/25
https://github.com/powertac/logtool-core/pull/6

There are currently no dedicated tests for state logging, as far as I know (I looked around for some when I split off the aop module). Should we add some? Perhaps that'd be a separate issue.
