### ISSUE TITLE
Use of powertac.version property defeats maven release process.

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#917]
The process of releasing the powertac-server multi-module currently requires the user to type in the release and development version numbers for each module to clear "remaining SNAPSHOT dependencies", after which it still fails saying `on project powertac-server: The version could not be updated: ${powertac.version}`. It is not clear exactly which instance of `${powertac.version}` it's complaining about at the end, possibly the one in the build clause under the maven-javadoc-plugin.

**Comment by erikkemperman** [comment]
The idea is, I believe, for each module to explicitly request its parent by version, inherit for itself that same version (implicitly by not specifying in its own pom) and then use the ${powertac.version} property that it inherits from that parent to include (sibling) dependencies.

This seems to work as expected, in local clean builds anyway, but it seems the maven-release-plugin doesn't get it? I've noticed it changes versions in poms (strip SNAPSHOT) -- maybe it's not finding all the right places to do that.

That would leave unresolvable relations, but parent-child or between siblings I'm not sure. Maybe see which helps, providing explicit versions for former and latter? 

There might be a standard maven property, ${project.parent.version} or something like that, doing the same as ${powertac.version} -- maybe that helps the plugin find siblings?

**Comment by jecollins** [comment]
Removing the use of ${powertac.version} did not fix the problem, but got us further. All the modules appear to have gotten through the release:prepare transformation other than visualizer2, which appears to want to resolve all the (un-built) release-version server components during the release:prepare phase. It seems that the mvn goals at the point of failure were `clean verify`. Does the viz2 build do things in the verify phase that require the rest of the system to be already built?

**Comment by jecollins** [comment]
I believe the core problem with ${powertac.version} is that it forces the release:prepare phase to resolve dependencies on modules that are not yet available. We release powertac-server after powertac-core is already released, and so the ${powertac.version} property, inherited from powertac-core, is actually incorrect at the start of the powertac-server release process. Perhaps each composite module needs its own version property? Not sure.

**Comment by erikkemperman** [comment]
If viz2 does magic during verify it properly got that from Jhipster, I'll look into it tomorrow.

**Comment by erikkemperman** [comment]
Sorry, _probably_.

**Comment by erikkemperman** [comment]
The ideal behaviour, single-step release of multiple modules, seems to be impossible in our setup, because the maven-release-plugin simply doesn't work across git repository boundaries (such as our git submodules). See [here](http://stackoverflow.com/questions/13378608/releasing-multiple-maven-artifacts-when-using-nested-git-submodules).

To be exact it fails during the step where the plugin wants to add/commit the changes it made the the various POMs.

So unless we change the repository boundaries (basically use a single repository containing all modules in, e.g., powertac-core) we'll have some manual work per submodule. I think it might not be worth the hassle of changing this, given that releases aren't that frequent?

Having said that, I notice that well-known multi-module projects I could think of all use a single repository, see for instance [spring-framework](https://github.com/spring-projects/spring-framework).

Thoughts?

**Comment by jecollins** [comment]
That piece is four years old, and I'm pretty sure there's been a change or two since then that make it possible. But somehow the references between release "packages" needs to be resolvable during the release process, and that's the problem with powertac.version. I like the idea, and it works fine for building, but it does not work for release.

**Comment by erikkemperman** [comment]
Yes it's an old piece, but it does still seem to be an issue. Otherwise I'd expect projects like spring to take advantage of it...

The maven plugin just does a git add on all the poms it changed and that goes wrong across module boundaries. There's a custom multi module plugin, created 2015, that might help. But do we want to depend on something like that.

I think another problem with our setup is that the aggregate modules powertac-core and -server also refer to powertac-parent. I'm not sure that's needed and pretty sure it confuses the release process.

I'll look into this further tomorrow.

**Comment by jecollins** [comment]
The release is finished. Finishing required removing virtually all use of these version properties. However, a planned re-factoring to a single git repo for powertac-core and one for powertac-server may change that.
