### ISSUE TITLE
ArrayIndexOutOfBoundsException in Sim

### ISSUE THREAD

**Issue by govertbuijs** [powertac/powertac-server#922]
206776 ERROR server.CompetitionControlService: java.lang.ArrayIndexOutOfBoundsException: -23
.. org.powertac.genco.MisoBuyer.lambda$0(MisoBuyer.java:290)
.. java.util.ArrayList.forEach(ArrayList.java:1249)
.. org.powertac.genco.MisoBuyer.getForecastArray(MisoBuyer.java:290)
.. org.powertac.genco.MisoBuyer.computeWeatherCorrections(MisoBuyer.java:242)
.. org.powertac.genco.MisoBuyer.generateOrders(MisoBuyer.java:214)
.. org.powertac.genco.SimpleGencoService.activate(SimpleGencoService.java:152)

**Comment by jecollins** [comment]
This is a very strange error - it must mean that we are working with a mal-formed WeatherForecastPrediction. Anything else unusual going on when this happened? In any case, we should check the index and add a log.error output.

**Comment by erikkemperman** [comment]
I think I've seen this before, let me check...

**Comment by erikkemperman** [comment]
If I remember correctly, this was fixed by
https://github.com/powertac/genco/commit/80558b2a73859586ad32390fff288ed468564719

And it looks like this made it into the singe_repo setup correctly:
https://github.com/powertac/powertac-server/commit/80558b2a73859586ad32390fff288ed468564719

What version are we running here?

**Comment by govertbuijs** [comment]
1.4.1 release. 
I think this is a different error, the exception happened on line 290.

Nothing strange as far as i can see.
Partial log files are here : http://ts.powertac.org/log/issue_922/

**Comment by erikkemperman** [comment]
It looks quite similar, negative array index on the same array as before. But 1.4.1 definitely has this fix in so maybe it didn't cover all cases?

**Comment by jecollins** [comment]
This error is unrelated to the fix for #878, which had to do with generating indices for the daily and weekly profiles. [This error appears](https://github.com/powertac/genco/blob/bd57602bcdda1a5265ff10ec4fd294c1f3af74d4/src/main/java/org/powertac/genco/MisoBuyer.java#L290) to occur while converting a (possibly out-of-order) list of weather forecasts to a properly sorted array, using the offset values in the WeatherForecastPrediction instances. Those offsets range from 1-24; we subtract one to index a zero-based array. So it appears we may have corrupted data, assuming this was generated with the 1.4.1 server.

I inspected the logs supplied by Govert. First -23 is a very strange index value in this case. The index is found by subtracting one from the forecast offset as
  result[fcst.getForecastTime() - 1]

This is happening in TS 378; immediately after the error is logged we see the end of ts 378:

206776 INFO  server.CompetitionControlService: Wait for tick 19
211497 INFO  server.CompetitionControlService: Deactivated timeslot 379, start 2014-09-01T19:00:00.000Z

The last time (and the first time) weather data was gathered was 90 sec / 18 timeslots earlier, starting at ms 116576. 14 full sets of WFP instances are logged in the state log, followed by the first two instances of the 15th set. Then we see (at ms 116638) some customer activity, followed by (at ms 116646) the remaining 22 WFPs in the 15th set, followed by the 16th through 24th sets. All the sets have offsets 1-24. as expected

This was the first batch of weather data, retrieved at TS 360:
116499 INFO  server.WeatherService: Timeslot 360 WeatherService reports time to make request for weather data

There were a number of JMS exceptions around ms 191953, three timeslots before the problem. Probably this is unrelated; there's no obvious relationship.

**Comment by jecollins** [comment]
This problem IS happening in the trial runs. So far I've looked at games 5 and 6, and both show the problem. So I went to run a local game, and got an exception in the console (using mvn -Pweb2) thrown by the weather service:

```
com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.io.StreamException
cause-message       : 
class               : java.util.ArrayList
required-type       : java.util.ArrayList
converter-type      : com.thoughtworks.xstream.converters.collections.CollectionConverter
path                : /data/weatherForecasts
line number         : 1
class[1]            : org.powertac.server.WeatherService$Data
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
version             : 1.4.9
```

Perhaps the error is happening when a forecast is missing or incomplete?

Retrieval of weather data is getting well ahead of the sim, but probably this is intentional. In game 6, the first error happens in TS 474. Here are the forecasts for TS 473-475:

```
206001:org.powertac.common.WeatherForecast::57719::new::473::(57307,57308,57309,57310,57311,57312,57313,57314,57315,57316,57317,57318,57319,57320,57321,57322,57323,57324,57325,57326,57327,57328,57329,57330)
206001:org.powertac.common.WeatherForecast::57720::new::474::(57331,57332,57333,57334,57335,57336,57337,57338,57339,57340,57341,57342,57343,57344,57345,57346,57347,57348,57349,57350,57351,57352,57353,57354)
206001:org.powertac.common.WeatherForecast::57721::new::475::(57355,57356,57357,57358,57359,57360,57361,57362,57363,57364,57365,57366,57367,57368,57369,57370,57371,57372,57373,57374,57375,57376,57377,57378)
```

and here are the WFP instances for TS 474:

```
205967:org.powertac.common.WeatherForecastPrediction::57331::new::-21::16.0::17.0::0.0::0.39
205967:org.powertac.common.WeatherForecastPrediction::57332::new::-20::16.0::15.0::0.0::0.39
205967:org.powertac.common.WeatherForecastPrediction::57333::new::-19::15.0::14.0::0.0::0.39
205967:org.powertac.common.WeatherForecastPrediction::57334::new::-18::14.0::13.0::0.0::0.39
205967:org.powertac.common.WeatherForecastPrediction::57335::new::-17::14.0::13.0::0.0::0.39
205967:org.powertac.common.WeatherForecastPrediction::57336::new::-16::13.0::13.0::0.0::0.38
205967:org.powertac.common.WeatherForecastPrediction::57337::new::-15::12.0::13.0::0.0::0.38
205967:org.powertac.common.WeatherForecastPrediction::57338::new::-14::12.0::14.0::0.0::0.42
205967:org.powertac.common.WeatherForecastPrediction::57339::new::-13::11.0::14.0::0.0::0.45
205967:org.powertac.common.WeatherForecastPrediction::57340::new::-12::11.0::15.0::0.0::0.49
205967:org.powertac.common.WeatherForecastPrediction::57341::new::-11::14.0::17.0::0.0::0.46
205968:org.powertac.common.WeatherForecastPrediction::57342::new::-10::16.0::20.0::0.0::0.42
205968:org.powertac.common.WeatherForecastPrediction::57343::new::-9::19.0::22.0::0.0::0.39
205968:org.powertac.common.WeatherForecastPrediction::57344::new::-8::21.0::23.0::0.0::0.38
205968:org.powertac.common.WeatherForecastPrediction::57345::new::-7::22.0::24.0::0.0::0.38
205968:org.powertac.common.WeatherForecastPrediction::57346::new::-6::23.0::24.0::0.0::0.37
205968:org.powertac.common.WeatherForecastPrediction::57347::new::-5::24.0::25.0::0.0::0.38
205968:org.powertac.common.WeatherForecastPrediction::57348::new::-4::24.0::27.0::0.0::0.38
205968:org.powertac.common.WeatherForecastPrediction::57349::new::-3::24.0::28.0::0.0::0.39
205968:org.powertac.common.WeatherForecastPrediction::57350::new::-2::24.0::27.0::0.0::0.32
205968:org.powertac.common.WeatherForecastPrediction::57351::new::-1::23.0::27.0::0.0::0.24
205968:org.powertac.common.WeatherForecastPrediction::57352::new::0::22.0::26.0::0.0::0.17
205968:org.powertac.common.WeatherForecastPrediction::57353::new::1::20.0::23.0::0.0::0.18
205968:org.powertac.common.WeatherForecastPrediction::57354::new::2::17.0::21.0::0.0::0.19
```
Note the negative offset values. This is incorrect, and is clearly the cause of the exception.

**Comment by govertbuijs** [comment]
These errors come from the weather data (weird that they they haven't come up before).
I've fixed this in the weather server.
