### ISSUE TITLE
visualizer2/yarn.lock should not be under version control

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#995]
I have a git status that says yarn.lock is modified. But the header of that file says it is auto-generated and should not be edited. If that's true, it seems to me it should not be under version control. An indeed, if I delete it and start the server with mvn -Pweb2, it gets re-generated.

**Comment by erikkemperman** [comment]
According to the developers of yarn, the lock file should be committed, see e.g. here:
https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

It should only change after edits to package.json, I guess yours was altered because I forgot to commit mine when I recently addressed the github security notice before my first coffee...
